# Generated by Django 5.2.1 on 2025-06-10 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0004_alter_category_name_alter_product_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Саны')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Тауар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to=settings.AUTH_USER_MODEL, verbose_name='Пайдаланушы')),
            ],
            options={
                'verbose_name': 'Себет элементі',
                'verbose_name_plural': 'Себет элементтері',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
